# Generated by Django 5.0.4 on 2024-04-18 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OEEapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionlog',
            name='actual_output',
        ),
        migrations.RemoveField(
            model_name='productionlog',
            name='bad_products',
        ),
        migrations.RemoveField(
            model_name='productionlog',
            name='good_products',
        ),
        migrations.RemoveField(
            model_name='productionlog',
            name='total_products',
        ),
    ]
