# Generated by Django 5.0.4 on 2024-04-18 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OEEapp', '0002_remove_productionlog_actual_output_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_time', models.FloatField()),
                ('unplanned_downtime', models.FloatField()),
                ('ideal_cycle_time', models.IntegerField()),
                ('good_product', models.IntegerField()),
                ('bad_product', models.IntegerField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OEEapp.machine')),
                ('production_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OEEapp.productionlog')),
            ],
        ),
    ]
